Ext.define('NeqMobile.controller.Home', {
			extend : 'Ext.app.Controller',
			views : ['Viewport','patient.List'],
			models : ['Patient'],
			stores : ['Patients'],
			refs : [{
						selector : 'viewport > tabpanel > panel > list',
						ref : 'patientsList'
					}

			],

			init : function() {
				console.log('Init home controller');
				// getMyButton().setHandler(function(){alert('2333');});

				this.control({
							// example of listening to *all* button taps
							'button' : {
								'tap' : function() {
									console.log('There are'
											+ this.getPatientsStore()
													.getTotalCount()
											+ 'records');
									var bla = Ext.ComponentQuery.query('list');
									// bla[1].setStore(this.getPatientsStore());

								}
							}
						});

			},
			onLaunch : function() {
				console.log('onLaunch home controller');
				// The "getter" here was generated by specifying the
				// stores array (above)
				var stationsStore = this.getPatientsStore();

				stationsStore.load({
							callback : this.onStationsLoad,
							scope : this
						});
			},

			onStationsLoad : function() {
		//		this.getPatientsList().setStore(this.getPatientsStore());
			},

			onButtonClick : function() {
				alert('button clicked')
			}
		});